#!/bin/bash

# Set the brightness level with a zenity dialog box

# Dependencies: `xbacklight` or `light-git`, `zenity`

# Prefer the `light` package, use `xbacklight` if `light` not found
lvl=$(light -G)

# Lets round the float result
lvl=$(echo "($lvl+0.5)/1" | bc)

lvl=$(yad --image="/usr/share/icons/ePapirus/64x64/apps/preferences-system-brightness-lock.svg" --width=420 --borders=10 --button=OK:0 --scale --value ${lvl} --title "Brightness" --text "Set monitor brightness")

light -S ${lvl}
