#!/bin/bash

# This script displays battery icon according to the charge level and charging state

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `acpi`

bat=$(acpi -b)
state=$(echo ${bat} | awk '{print $3}')
icon_path="/usr/share/icons/Papirus/symbolic/status"

if [[ "$state" = "Not" ]]; then
    level=$(echo ${bat} | awk '{print $5}')
    level=${level::-1}

else
    level=$(echo ${bat} | awk '{print $4}')
    if [[ "$state" == *"Unknown"* ]]; then
        level=${level::-1}
    else
        if [[ "$level" == "100%" ]]; then
          level=${level::-1}
        else
          level=${level::-2}
        fi
    fi
fi

if [[ "$bat" == *"until"* ]]; then
    if [[ "$level" -ge "100" ]]; then
        echo "${icon_path}/battery-level-100-charged-symbolic.svg"
    elif [[ "$level" -ge "90" ]]; then
        echo "${icon_path}/battery-level-90-charging-symbolic.svg"
    elif [[ "$level" -ge "80" ]]; then
        echo "${icon_path}/battery-level-80-charging-symbolic.svg"
    elif [[ "$level" -ge "70" ]]; then
        echo "${icon_path}/battery-level-70-charging-symbolic.svg"
    elif [[ "$level" -ge "60" ]]; then
        echo "${icon_path}/battery-level-60-charging-symbolic.svg"
    elif [[ "$level" -ge "50" ]]; then
        echo "${icon_path}/battery-level-50-charging-symbolic.svg"
    elif [[ "$level" -ge "40" ]]; then
        echo "${icon_path}/battery-level-40-charging-symbolic.svg"
    elif [[ "$level" -ge "30" ]]; then
        echo "${icon_path}/battery-level-30-charging-symbolic.svg"
    elif [[ "$level" -ge "20" ]]; then
        echo "${icon_path}/battery-level-20-charging-symbolic.svg"
    elif [[ "$level" -ge "10" ]]; then
        echo "${icon_path}/battery-level-10-charging-symbolic.svg"
    elif [[ "$level" -ge "0" ]]; then
        echo "${icon_path}/battery-level-0-charging-symbolic.svg"
    fi
else
    if [[ "$level" -ge "100" ]]; then
        echo "${icon_path}/battery-level-100-charged-symbolic.svg"
    elif [[ "$level" -ge "90" ]]; then
        echo "${icon_path}/battery-level-90-symbolic.svg"
    elif [[ "$level" -ge "80" ]]; then
        echo "${icon_path}/battery-level-80-symbolic.svg"
    elif [[ "$level" -ge "70" ]]; then
        echo "${icon_path}/battery-level-70-symbolic.svg"
    elif [[ "$level" -ge "60" ]]; then
        echo "${icon_path}/battery-level-60-symbolic.svg"
    elif [[ "$level" -ge "50" ]]; then
        echo "${icon_path}/battery-level-50-symbolic.svg"
    elif [[ "$level" -ge "40" ]]; then
        echo "${icon_path}/battery-level-40-symbolic.svg"
    elif [[ "$level" -ge "30" ]]; then
        echo "${icon_path}/battery-level-30-symbolic.svg"
    elif [[ "$level" -ge "20" ]]; then
        echo "${icon_path}/battery-level-20-symbolic.svg"
    elif [[ "$level" -ge "10" ]]; then
        echo "${icon_path}/battery-level-10-symbolic.svg"
    elif [[ "$level" -ge "0" ]]; then
        echo "${icon_path}/battery-level-0-symbolic.svg"
    else
        echo "${icon_path}/battery-empty-symbolic.svg"
    fi
fi
if  [[ $1 = "-l" ]]; then
    echo ${level}%
fi
